### ISSUE TITLE
Error getting WAVES balance

### ISSUE THREAD

**Issue by morbiuslevakov** [wavesplatform/WavesJ#125]
Hello! I tried to get my WAVES balance, but I got the error: Invalid asset id.
My code:
`Node node = new Node(Profile.MAINNET);
Address address = new Address("3PPPdfdNBLXPGJJVO5KAUS116JUTr6GvNDd");
node.getAssetBalance(address, AssetId.WAVES);`

Maybe I'm doing something wrong. Help me please)

**Comment by br0x** [comment]
WAVES is not an asset. Use getBalance / getBalances endpoints
