### ISSUE TITLE
Q. not supported to async?

### ISSUE THREAD

**Issue by Bang9** [wavesplatform/WavesJ#24]
only support to synchronous request?
have you plan to support async update?

**Comment by Tolsi** [comment]
Yes, only sync api for now. What is your favorite instrument to work with async stuff in java? java.util.concurrent.Future?

**Comment by Bang9** [comment]
I don't use Java very often, but I think I've used Future once!
I'm writing now WavesJ into react-native bridge module for android, because this library is nice and simple to use ever in waves in my opinion.. anyway, almost finished base part of to use, but I faced problem that screen is stopped in react-native when I request to WavesJ.. so sad
Can you write async api?
