### ISSUE TITLE
"Invalid cookie header" in logs

### ISSUE THREAD

**Issue by atemerev** [wavesplatform/WavesJ#3]
With almost any API request, the following warning is printed to stderr:

WARNING: Invalid cookie header: "Set-Cookie: AWSALB=[REDACTED]; Expires=Tue, 13 Feb 2018 12:31:29 GMT; Path=/". Invalid 'expires' attribute: Tue, 13 Feb 2018 12:31:29 GMT

**Comment by atemerev** [comment]
I have created a pull request for this: 

https://github.com/wavesplatform/WavesJ/pull/4

(See https://stackoverflow.com/questions/36473478/fixing-httpclient-warning-invalid-expires-attribute-using-fluent-api for further background.)

**Comment by petermz** [comment]
Fixed in 18c9182513a0aa1dd8e27299274a333c2b82c13f
I rather ignore cookies altogether, no use for them anyway

**Comment by petermz** [comment]
No, I was wrong -- these cookies are set by load balancer and might well make sense. So I've merged your version of the fix, thanks!
