### ISSUE TITLE
wavesj is broken on mainnet

### ISSUE THREAD

**Issue by br0x** [wavesplatform/WavesJ#35]
I checked maven artifact 0.15.0
OrderDeserializer deserialize:
NPE at 
int version = objectMapper.treeToValue(treeNode.get("version"), Integer.class);

Please recall it from maven repo

**Comment by msmolyakov** [comment]
Please update to WavesJ 1.0.0 and try to deserialize order by `Order.fromJson(String json)` method. It works now.
