### ISSUE TITLE
OrderRejected

### ISSUE THREAD

**Issue by EmersonCaique** [wavesplatform/WavesJ#54]
public class SpreadBot {
    private final long maxOrderSize = 1 * Asset.MILLI; // in priceAsset
    private final double halfSpread = 0.01; // 1%
    private final long fee = 3 * Asset.MILLI; // in WAVES
    private final long period = 60000; // 1 min

    private final PrivateKeyAccount account;
    private final AssetPair market;
    private final Node node, matcher;
    private final String matcherKey;

    public static SpreadBot mainnetInstance() throws IOException, URISyntaxException {
        String nodeUrl = "https://nodes.wavesplatform.com";
        String matcherUrl = "https://matcher.waves.exchange/matcher";
        return new SpreadBot(
                PrivateKeyAccount.fromPrivateKey(MY_CORRECT_PRIVTE_KEY, Account.MAINNET),
                new AssetPair(Asset.WAVES, "8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"), matcherUrl, nodeUrl, 'W');
    }

    private SpreadBot(PrivateKeyAccount account, AssetPair market, String matcherUrl, String nodeUrl, char chainId)
            throws IOException, URISyntaxException {
        this.account = account;
        this.market = market;
        this.node = new Node(nodeUrl, chainId);
        this.matcher = new Node(matcherUrl, chainId);
        this.matcherKey = matcher.getMatcherKey();
    }

    private void cancelOrder(String orderId) throws IOException, InterruptedException {
        String status = matcher.cancelOrder(account, market, orderId);
        System.out.printf("%s %s\n", status, orderId);
    }

    private String fileOrder(Order.Type type, long price, long amount) throws IOException, InterruptedException {
        long expiration = System.currentTimeMillis() + Math.max(period, 61000); // matcher requires expiration > 1 min
                                                                                // in the future
        Order order = matcher.marketOrder(account, matcherKey, market, type, price, amount, expiration, fee);
        System.out.printf("Filed order %s to %s %d at %d\n", order.getId(), type, amount, price);
        return order.getId().getBase58String();
    }

    private void round() throws IOException, InterruptedException {
        System.out.println();
        System.out.printf("Current balance  in %s is %d", market.getAmountAsset(),
                node.getBalance(account.getAddress(), market.getAmountAsset()));

        System.out.printf("Current balance  in %s is %d", market.getPriceAsset(),
                node.getBalance(account.getAddress(), market.getPriceAsset()));

        // Cancel all orders filed at our market
        for (Order order : matcher.getOrders(account, market)) {
            if (order.isActive()) {
                cancelOrder(order.getId().getBase58String());
            }
        }

        // Read order book
        OrderBook book = matcher.getOrderBook(market);
        if (book.getBids().size() <= 0) {
            System.out.println("There are no bids, skipping this round");
            return;
        }
        if (book.getAsks().size() <= 0) {
            System.out.println("There are no asks, skipping this round");
            return;
        }

        // Determine buy and sell prices
        long bestBid = book.getBids().get(0).getPrice();
        long bestAsk = book.getAsks().get(0).getPrice();
        System.out.printf("Spread %d : %d\n", bestBid, bestAsk);
        long meanPrice = (bestBid + bestAsk) / 2;
        long buyPrice = (long) (meanPrice * (1 - halfSpread));
        long sellPrice = (long) (meanPrice * (1 + halfSpread));

        // Find out how much we want to buy, and file an order
        long priceAssetAvail = node.getBalance(account.getAddress(), market.getPriceAsset()) - 2 * fee;
        if (priceAssetAvail > 0) {
            long buyOrderSize = Math.min(priceAssetAvail, maxOrderSize) * Asset.TOKEN / buyPrice;
            fileOrder(Order.Type.BUY, buyPrice, buyOrderSize);
        }

        // Same for sell order
        long amountAssetAvail = node.getBalance(account.getAddress(), market.getAmountAsset()) - 2 * fee;
        if (amountAssetAvail > 0) {
            long sellOrderSize = Math.min(amountAssetAvail, maxOrderSize * Asset.TOKEN / sellPrice);
            fileOrder(Order.Type.SELL, sellPrice, sellOrderSize);
        }
    }

    private class RoundTask extends TimerTask {
        @Override
        public void run() {
            try {
                round();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void run() {
        Timer t = new Timer();
        t.schedule(new RoundTask(), 0, period);
    }

    public static void main(String[] args) throws IOException, URISyntaxException {
        SpreadBot.mainnetInstance().run();
    }
}

**Comment by EmersonCaique** [comment]
{"result":null,"template":"Required one of the following fee asset: {{required}}. But given \"WAVES\" as Base58 string. Remove this field if you want to specify WAVES in JSON","success":false,"error":9441540,"message":"Required one of the following fee asset: 474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu, 8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS, WAVES. But given \"WAVES\" as Base58 string. Remove this field if you want to specify WAVES in JSON","params":{"required":["474jTeYx2r2Va35794tCScAXWJG9hU2HcgxzMowaZUnu","8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS","WAVES"]},"status":"OrderRejected"}
        at com.wavesplatform.wavesj.Node.exec(Node.java:676)
        at com.wavesplatform.wavesj.Node.placeOrder(Node.java:527)
        at com.wavesplatform.wavesj.Node.marketOrder(Node.java:554)
        at com.trade.waves.tradewaves.SpreadBot.fileOrder(SpreadBot.java:47)
        at com.trade.waves.tradewaves.SpreadBot.round(SpreadBot.java:97)
        at com.trade.waves.tradewaves.SpreadBot.access$0(SpreadBot.java:52)
        at com.trade.waves.tradewaves.SpreadBot$RoundTask.run(SpreadBot.java:105)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)


i get this error

**Comment by tryphe** [comment]
I think it's complaining that the Json for the market `WAVES_BTC` should look like this:
`assetPair":{"amountAsset":null,"priceAsset":"8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS"}`
Where `WAVES` is null and not `WAVES.

And in binary, `WAVES` = `0x00`, and anything else = `0x01 + <32 decoded base58 bytes>`.

**Comment by msmolyakov** [comment]
Since 1.0.0 version WavesJ supports only Waves Node API. Therefore, unfortunately, it doesn't support Matcher API.

To deal with the matcher, you can use [ccxt](https://docs.waves.exchange/en/ccxt/) library. Or create your own based on WavesJ for orders signing and serialization.
