### ISSUE TITLE
Any example of Matcher working?

### ISSUE THREAD

**Issue by Kylix69** [wavesplatform/WavesJ#58]
Hello, 

I cannot get ** any ** of the WavesJ Matcher tests or examples working on testnet. 
I can get them working using WavesCS (.Net).

Even when I change the urls to the following ... 

Wave Node : "https://testnode4.wavesnodes.com" 
Matcher node : "https://matcher-testnet.wavesnodes.com"

I keep getting OrderRejected Messages. This happens to both calls to matcher.createOrder() and matcher.placeOrder().

Passing null to matcherFeeAssetId in the placeOrder() method seems to bypass the first issue I have (thus we cannot use createOrder()). But the placeOrder() method throws various error messages afterwards. One of which is ... "The order is invalid: SpendAmount should be > 0"

The Account I am using has enough WAVES and I can use the exact same account from WavesCS and the order goes through. So something is wrong with the Java implementation.

I also noticed that the java version has not been updated for quite a while, whereas the WavesCS version has been updated. Is WavesJ still supported?

Best,
Toy

**Comment by Kylix69** [comment]
Further to this, is it possible to have the test cases corrected in the WavesJ code, so all tests pass? I'm looking for at least one working example of Matcher.

Best,
Toy.

**Comment by msmolyakov** [comment]
Hi, @Kylix69 !
The current version of the library is outdated a bit and not maintained, but now a new version is being actively developed. It will support all the new features of the upcoming release of Waves Node 1.2.
Unfortunately, WavesJ will no longer support Matcher REST API. But most likely a separate library will appear for this.
