### ISSUE TITLE
Token create

### ISSUE THREAD

**Issue by lubiku** [wavesplatform/WavesJ#63]
I want creat token with wave can i have any instructions ?

**Comment by msmolyakov** [comment]
Could you describe in more detail your issue?

**Comment by lubiku** [comment]
I would like creat token with wave plateform and i want have any base

**Comment by msmolyakov** [comment]
Using WavesJ? You can see example of asset issue here:

https://github.com/wavesplatform/WavesJ/blob/master/examples/src/main/java/NodeExample.java#L52

**Comment by msmolyakov** [comment]
Closed. Feel free to reopen it again, please, if your issue is still actual.
