### ISSUE TITLE
Pump README.md

### ISSUE THREAD

**Issue by msmolyakov** [wavesplatform/WavesJ#67]
Write a comprehensive description of all features and possible usages:

- how to generate or import account
- how to connect to official and own nodes and make requests
- which endpoints can be requested
- how to create, sign and send transactions of each type
- how transaction fields are filled with default values
- and etc

**Comment by alter** [comment]
Use our lessons:
https://dev.waves.tech/edu/lessons
There is a lot of information about working with SDKs.
