### ISSUE TITLE
how can  i get  this jar (com.wavesplatform:protobuf-schemas:pom:1.2.6-SNAPSHOT)

### ISSUE THREAD

**Issue by lfj7282** [wavesplatform/WavesJ#75]
hi ，when i import  WavesJ in my  project.
like this

          <dependency>
              <groupId>com.wavesplatform</groupId>
              <artifactId>wavesj</artifactId>
              <version>1.0.1</version>
          </dependency>

i found this jar denpendencys in pom.xml like this:

       <dependency>
            <groupId>im.mak</groupId>
            <artifactId>waves-transactions</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.wavesplatform</groupId>
            <artifactId>protobuf-schemas</artifactId>
            <version>1.2.6</version>
        </dependency>
        <dependency> 
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.12.2</version>
        </dependency>

**there "protobuf-schemas" version is 1.2.6.
but the waves-transactions pom.xml denpendendy  protobuf-schemas version is 1.2.6-SNAPSHOT**
        
        <dependency>
            <groupId>im.mak</groupId>
            <artifactId>waves-crypto</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.wavesplatform</groupId>
            <artifactId>protobuf-schemas</artifactId>
            <version>1.2.6-SNAPSHOT</version>
        </dependency>

i can not find this version 1.2.6-SNAPSHOT in maven repository.

**and there is a bug if waves-transactions  denpendency protobuf-schemas version 1.2.6.**
the class im.mak.waves.transactions.serializers.ProtobufConverter  method fromProtobuf
can not find class com.wavesplatform.protobuf.transaction.TransactionOuterClass.Transaction in  protobuf-schemas for version 1.2.6.

can anyone fix it?
thanks

**Comment by msmolyakov** [comment]
Thanks, @lfj7282, we will fix it.

**Comment by msmolyakov** [comment]
Fixed in WavesJ 1.0.4. Protobuf-schemas is used as waves-transactions dependency and updated to 1.2.10 version.
