### ISSUE TITLE
WavesJ dependency issue In Gradle

### ISSUE THREAD

**Issue by DunkanMcLoud** [wavesplatform/WavesJ#77]
When trying to add dependency in gradle received such an error

> Could not resolve com.wavesplatform:wavesj:1.0.1.
         > inconsistent module metadata found. Descriptor: com.wavesplatform:wavesj:1.0.1-SNAPSHOT Errors: bad version: expected='1.0.1' found='1.0.1-SNAPSHOT'

the similar mistake takes place in version 1.0.0

Maven dependency works Ok

**Comment by msmolyakov** [comment]
Fixed. Should work now on WavesJ 1.0.4.
